### PR TITLE
feat: Ajust Features styles with round and gaps & better titles spacing

### PR DESCRIPTION
**Pull request by t1gu1**
## 📑 Description

I simply want to add a tiny touch to make things looks a bit nicer

- Add radius and gap to "Features" elements
- I arrange feature order to make the one line feature title with the others one line and the two lines feature title on the same line.
- Ajust general section spacing to add a bit more bottom spacing (Faq **was** a bit closer of "Features section" than "Faq" section) (Very very small ajustement)

#### Before:

image

#### After:

image

Looks nice on smaller screen and mobile too

image

#### Before

image

#### After

image

### CODE REVIEW

**Review by mehalter — CHANGES_REQUESTED** [review]
Thanks for this! I enjoy everything except the reordering of the features. We definitely want to keep the features in the order we had them, basically in order of most "important"-ish? The biggest thing is getting AstroCommunity to the very first place. I would be open to rewording these if you want to keep them grouped by title length

**Comment by mehalter** [comment]
Oh also, @t1gu1 along with the adjustments back to the original feature order, let me know if you are participating in Hacktoberfest and I can add the appropriate label to the PR 😄

**Comment by t1gu1** [comment]
Ok, I'll leave the features order as before.

I think you get the concept.
It will be free to you to ajust features titles later if you want. :)

---

Oh, I just see that's the Hacktoberfest event as I read you.
I just register. So yeah it could be nice. Thx

**Review by mehalter — APPROVED** [review]
LGTM! Thanks for the contribution, these style updates look great

**Pull request merged**
